### ISSUE TITLE
Why does a valueMap not have a specific termMap subclass?

### ISSUE THREAD

**Issue by arenas-guerrero-julian** [kg-construct/rml-fnml#14]
Hi there,

In the RML+FnO spec, subject, predicate, parameter, [...] maps have an associated subclass of the termMap class.

I wonder what is the rationale behind not having a specific (termMap) subclass for value maps.

**Comment by bjdmeest** [comment]
Given we don't introduce a definition for the object of a valueMap predicate different from the original TermMap definition, I guess there didn't seem to be a clear reason to introduce a new concept, but feel free to give feedback on that :)

**Comment by bjdmeest** [comment]
I personally don't see a benefit, as the definition is exactly the same, but we can discuss during the bi-weekly :)

**Comment by DylanVanAssche** [comment]
Is this still applicable since everything except Function Execution is now a Term Map?

**Comment by bjdmeest** [comment]
It's still applicable. I personally think that having an additional class with the same definition is more misleading and unnecessarily constraining the ontology, but I don't think we reached consensus on that yet.

**Comment by samiscoding** [comment]
Adding the ExpressionMap as a "block" involving the execution and the output which are each defined as term maps, I think we have a good definition. Maybe we can conclude this issue if everyone agrees.

**Comment by bjdmeest** [comment]
Consensus! Closing!
