### ISSUE TITLE
Use newly introduced ExpressionMap as domain for execution, return, and returnMap

### ISSUE THREAD

**Issue by pmaria** [kg-construct/rml-fnml#16]
With the introduction of `rml:ExpressionMap`, the domain of `rml:execution` , `rml:return`, and `rml:returnMap`, should now be changed to `rml:ExpressionMap`.
This makes functions applicable on anything that is an `rml:ExpressionMap` , like `rml:DatatypeMap`, `rml:LanguageMap` etc.

**Comment by bjdmeest** [comment]
Ah no, ignore my previous comment

**Comment by bjdmeest** [comment]
@anaigmo

**Comment by anaigmo** [comment]
> @pmaria are we supposed to call it 'function-valued expression map' then as well?

I'm confused by this statement, do you mean by this to introduce also a subclass of ExpressionMap called like that?

**Comment by bjdmeest** [comment]
We should be able to use a function when creating, e.g., the language tag, can you estimate how this affects the current diagram @anaigmo ? I would expect that all lines that currently go from FNML to TermMap as I see them at [ontology/RML diagrams-RML-overview.png](https://github.com/kg-construct/rml-core/blob/054fcafe14dfe1c394293bae418d4fa0257ad53c/ontology/RML%20diagrams-RML-overview.png) should actually go to ExpressionMap. But I could be wrong :)

**Comment by anaigmo** [comment]
Oki let's see; there are two options:
1) We go for ExpressionMap for everything: All terms that previously were subclass of TermMap, now they are of ExpressionMap

![RML-diagram-RML (Functions)](https://user-images.githubusercontent.com/36294992/234784927-ca62a73a-7c1b-4da9-835d-62213089438d.png)

2) We only change the domains of returnMap, return and execution; leaving the rest with termMap

![RML-diagram-RML (Functions) (1)](https://user-images.githubusercontent.com/36294992/234784970-555ec942-dcf3-46fc-b321-dc760112f875.png)

(Note that in the diagrams I'm not showing the shortcuts, but I take them into account for the OWL) 

Please confirm which option makes more sense, and I'll change the corresponding resources

**Comment by bjdmeest** [comment]
The latter makes most sense imo, and is in line with what @pmaria said, so I vote for 2! :D

**Comment by samiscoding** [comment]
The second diagram makes more sense to me too!

**Comment by bjdmeest** [comment]
TODO @bjdmeest fix the spec wording

**Comment by bjdmeest** [comment]
So, this was already fixed 🙈
