### ISSUE TITLE
Issues with test cases

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/rml-fnml#33]
- [x] 0000 relies on a UUID function, but that always yields a different result
- [x] Tests still rely on old representations of sources
- [x] should the `rml:constant "name" ;` in 0002 not be changed to `rml:reference "name" ;` The test description states that it tests whether the "false reference" is caught, but the test uses a constant and I do not see what is wrong with this mapping. The spec does not specify that constant expression maps are not allowed for input value maps.
- [x] Is `id-lab:toUpperCaseURL` a good function for test case 0004? It is underspecified and it does not play nicely with the usual behavior of trying to generate an absolute IRI. I would have understood it the test data contained a IRI, but the test case now assumes that the values is put next to `http://` 
- [x] `http://VENUS` is not a valid absolute IRI
- [x] Ibid for 0005
- [x] 0006 -> the function adds `http:\\` (lower case) when it is missing, but transforms `http://` into `HTTP://` when it is provided.
- [x] We should have a variant with `rml:return` other than the nested function call. Maybe 0001?

**Comment by chrdebru** [comment]
I proposed a PR for the second issue.

**Comment by bjdmeest** [comment]
I fixed the third issue in #37

**Comment by bjdmeest** [comment]
Added a suggestion for the first issue in #38 , but in this stage I prefer not to replace existing test cases but rather create more if it's an alternative instead of a bugfix, hence the `0000b`

**Comment by bjdmeest** [comment]
made a suggestion for the 4th issue in #39

**Comment by bjdmeest** [comment]
made a suggestion for the 6th issue in #40

**Comment by chrdebru** [comment]
All looks good. There is just one problem with `0010` --> it fails the shape files.

```
        rml:objectMap [
            rml:functionExecution <#Execution> ;
            rml:returnMap [
                rml:constant fns:domainOutput
            ]
        ]
```

But:
```
Node=_:B2b96fcbd08ae031e639d8d104ab45f88
  Path=(((<http://w3id.org/rml/template>|<http://w3id.org/rml/constant>)|<http://w3id.org/rml/reference>)|<http://w3id.org/rml/returnMap>)|<http://w3id.org/rml/functionExecution>
  Message: 
        Exactly one rml:template, one rml:constant, one rml:reference,
        one rml:returnMap, or one rml:functionExecution is required.
```
And this one has both a returnMap and rml:FunctionExecution.

**Comment by dachafra** [comment]
Hi @bjdmeest @chrdebru, can we close this issue and find a solution of the problem mentioned by @chrdebru in a new one?

**Comment by bjdmeest** [comment]
yeah I made https://github.com/kg-construct/rml-core/issues/142, so then all tasks of _this_ issue are done
