### ISSUE TITLE
Enabling conditions on functions

### ISSUE THREAD

**Issue by igrangel** [kg-construct/rml-fnml#47]
Hi all, 

There are many cases where we need to have conditions as output of the mappings, similar to what is described [here](https://github.com/oeg-upm/yatter/issues/80). 

These are just some of concrete use cases we have, but there are many more. 

- When a given field is empty, the triple is not created
- When a field represent ranges we need to be able to create instances for each value in the given range, e.g., XYZ12,14, means that we need to obtain three instances, i.e., ex:XYZ12, ex:XYZ13, and ex:XYZ14
- When a field contains strings that should be split into two properties given a specific pattern

**Comment by dachafra** [comment]
Hi @igrangel, @bjdmeest has proposed the conditions in functions https://kg-construct.github.io/rml-fnml/spec/docs/#conditions. We can close this issue as it's complete, and if you have any comment you can open a new issue or a PR.
